output "cluster_id" {
  description = "cluster id as generated by the module."
  value = module.aws-eks.cluster_id
}

output "kubeconfig" {
  description = "kubectl config as generated by the module."
  value = module.aws-eks.kubeconfig
}

output "worker_iam_role_name" {
  description = "Worker IAM role name of the EKS cluster."
  value       = module.aws-eks.worker_iam_role_name
}