output "kubeconfig" {
  description = "kubectl config as generated by the module."
  value = module.aws-eks.kubeconfig
}

output "worker_sg_id" {
  description = "worker security group id"
  value = aws_security_group.worker.id
}